services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: digimenu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
